all:
  hosts:
    remote:
      ansible_connection: ssh
      ansible_user: vagrant # Remote user
      ansible_host: 192.168.0.24 # Remote host
      ansible_port: 22
      site_name: mysite.com
      hos_repo_url: https://github.com/avorobyov20/hos.git
      hos_repo_version: master
