all:
  hosts:
    remote:
      site_name: mysite.com
      ansible_user: vagrant # --> {{ remote_user }}
      ansible_connection: ssh
      ansible_port: 22
      # ansible_host: 192.168.0.24 # Remote host
